# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a9274d9e0a9573d567038dc973a3f2644b249606bb5671ec489ed394ed8a2dfaf0ba131dcee5a20b0f2f232ae2474aa93f84856fc80a9b96c840f86c2ab3a7a

test:
  secret_key_base: 1aaaa1ee4bb0192683d307ba742536199e8d8c77c6d2c7e51f04ad518792c93ba9e335afee5078438825260b0624546c857fc3b602102793161d864f027744ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
